
# git ??? ?? ???
server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://project1.cxg8vdlfu0la.ap-southeast-2.rds.amazonaws.com:3306/dev
    #    username: admin
    #    password: '00000000'
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # DDL?? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true # ??? ?? ??



  # yaml/yml ?? - Thymeleaf ??
  thymeleaf:
    cache: false
    check-template-location: true
    #    prefix: classpath:/templates/
    #    suffix: .html
    enabled: true

